### ISSUE TITLE
Onnx model lacking metadatas to run other enviroments

### ISSUE THREAD

**Issue by testBas** [ankandrew/open-image-models#2]
Working model Properties (https://netron.app/)
![working model](https://github.com/user-attachments/assets/142d0943-f2b2-45b7-8288-0fc1bd4c5ca7)

yolo-v9-t-256-license-plates-end2end.onnx (not working)
![not working](https://github.com/user-attachments/assets/0ac4ce93-d3eb-48e7-acb3-823b5c6c8dcf)

I couldn't find any way to edit this properties to make it run could you please help me? I think we need,
version, stride, task, batch, imgsz, names
this metadata added to model.

First i tried it with c# Onnx.runtime it was giving errors(loading), then Yolodotnet example code couldn't run it gives error while the loading onnx model.
using var yolo = new Yolo(new YoloOptions
{
    OnnxModel = @"yolo-v9-t-256-license-plates-end2end.onnx",      // Your Yolo model in onnx format
    ModelType = ModelType.ObjectDetection,  // Set your model type
    Cuda = false,                           // Use CPU or CUDA for GPU accelerated inference. Default = true
    GpuId = 0,                              // Select Gpu by id. Default = 0
    PrimeGpu = false,                       // Pre-allocate GPU before first inference. Default = false
});
System.Collections.Generic.KeyNotFoundException: 'The given key 'task' was not present in the dictionary.'

**Comment by ankandrew** [comment]
Probably the reason that's failing with [YoloDotNet](https://github.com/NickSwardh/YoloDotNet), it's because it doesn't expect the end2end model, which has NMS embedded in it's graph. Look at the assets, I provide PyTorch models too https://github.com/ankandrew/open-image-models/releases/tag/assets. Just export that without end2end.

**Comment by testBas** [comment]
Can you please give me example python code for this, i have no experience about image models
Trying to run
`import torch

device = torch.device('cpu')
model = torch.load('yolo-v9-t-256-license-plates.pt', map_location=device)['model'].float()
torch.onnx.export(model, torch.zeros((1, 1, 256, 256)), 'yolov9.onnx')`

ModuleNotFoundError: No module named 'models'

**Comment by ankandrew** [comment]
Use this script to export to ONNX format the YoloV9 https://github.com/WongKinYiu/yolov9/blob/main/export.py. Export with `onnx` instead of `onnx_end2end`, which includes NMS.
